version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      TZ: 'UTC'
      MYSQL_DATABASE: 'paymentServiceDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'hello123'
      MYSQL_ROOT_PASSWORD: 'nekiJakiPassword-123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - feri-mag-ita:/var/lib/mysql
    networks:
      - feri-mag-ita-network

  paymentservice:
    build: ./paymentservice/
    ports: 
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - feri-mag-ita-network
    depends_on:
      - db

  ticketmachineservice:
    build: ./ticketmachineservice/
    ports:
      - '8081:8080'
    expose:
      - '8081'
    networks:
      - feri-mag-ita-network
    depends_on:
      - db

volumes:
  feri-mag-ita:

networks:
  feri-mag-ita-network: