version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      TZ: 'UTC'
      MYSQL_DATABASE: 'paymentServiceDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'hello123'
      MYSQL_ROOT_PASSWORD: 'nekiJakiPassword-123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - feri-mag-ita:/var/lib/mysql
    networks:
      - feri-mag-ita-network

  paymentservice:
    build: ./paymentservice/
    environment:
      - JAKARTA_PERSISTANCE_JDBC_URL=jdbc:mysql://mysql:3306/paymentServiceDb?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/paymentServiceDb?useSSL=false&serverTimezone=UTC
    ports: 
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - feri-mag-ita-network
    depends_on:
      - mysql

  ticketmachineservice:
    build: ./ticketmachineservice/
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/paymentServiceDb?useSSL=false&serverTimezone=UTC
    ports:
      - '8081:8080'
    expose:
      - '8081'
    networks:
      - feri-mag-ita-network
    depends_on:
      - mysql

volumes:
  feri-mag-ita:

networks:
  feri-mag-ita-network: